# Generated by Django 4.2 on 2026-02-23 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('default_model', models.CharField(default='EfficientNet-B0', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('data_retention_days', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('progressed_image', models.ImageField(blank=True, null=True, upload_to='progressions/')),
                ('current_age', models.IntegerField(default=0)),
                ('target_age', models.IntegerField()),
                ('model_used', models.CharField(default='Age-cGAN', max_length=50)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('predicted_age', models.IntegerField()),
                ('confidence', models.FloatField(default=0.0)),
                ('gender', models.CharField(default='Unknown', max_length=20)),
                ('emotion', models.CharField(default='Unknown', max_length=30)),
                ('face_count', models.IntegerField(default=1)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
