# Generated by Django 5.2 on 2026-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agevision_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionrecord',
            name='aging_insights',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='progressionrecord',
            name='gender',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='progressionrecord',
            name='pipeline_steps',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='progressionrecord',
            name='model_used',
            field=models.CharField(default='StyleGAN3', max_length=50),
        ),
    ]
