# Generated by Django 5.2 on 2026-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agevision_api', '0002_progressionrecord_aging_insights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='confidence_threshold',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='data_retention_days',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_detect_faces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='high_accuracy_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='save_to_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_confidence',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_model',
            field=models.CharField(default='DeepFace v3', max_length=50),
        ),
    ]
