# Generated by Django 5.2 on 2026-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agevision_api', '0003_remove_usersettings_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='age_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='detector_used',
            field=models.CharField(default='opencv', max_length=30),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='ensemble_ages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='race',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
