"""
Django settings for agevision_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local config. If the file is absent, load_dotenv is a no-op and
# values fall back to real environment variables / the defaults below.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-$w-u165_=gjg-&(605ll1muhoyns_@*pi-gzi8e=7w7!_7-)_g'
)

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'agevision_api',
    'age_progression',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agevision_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agevision_backend.wsgi.application'


# Database
# SQLite for Django internals only (auth User model, admin, sessions, migrations)
# MongoDB (via PyMongo) is the primary data store for ALL application data:
#   predictions, progressions, user settings, user profiles, password resets

# SQLITE_PATH optionally relocates the auth DB (users, sessions, JWT blacklist).
# Defaults to db.sqlite3 in the project dir for the local setup.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}

# MongoDB Configuration (accessed via PyMongo in views)
MONGO_URI = os.environ.get('MONGO_URI', '')
MONGODB_CONFIG = {
    'HOST': os.environ.get('MONGO_HOST', 'localhost'),
    'PORT': int(os.environ.get('MONGO_PORT', '27017')),
    'NAME': os.environ.get('MONGO_DB', 'agevision_db'),
    'URI': MONGO_URI,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS Settings
_cors_origins_env = os.environ.get('CORS_ORIGINS', 'http://localhost:4200')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(',') if o.strip()]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins — needed for the Django admin / forms once the site is
# served over the public HTTPS domain. Comma-separated, e.g.
# "https://agevision.example.com". Empty in plain local use.
_csrf_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(',') if o.strip()]

# Behind nginx + Cloudflare Tunnel, TLS is terminated upstream and the request
# reaches Django over HTTP. Trust the forwarded proto/host so request.is_secure()
# and build_absolute_uri() produce correct https:// URLs (used for media links).
if os.environ.get('BEHIND_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# REST Framework + JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    # Short-lived access token: if leaked, exposure window is ≤15 minutes.
    # The Angular auth interceptor silently calls /token/refresh/ on any 401
    # and replays the original request, so this is invisible to the user.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),

    # Refresh token gives the session a 7-day idle window. After 7 days
    # of no API activity, the user must log in again.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Issue a brand-new refresh token on every refresh call (sliding session)
    # and immediately blacklist the old one. If a refresh token leaks, the
    # next legitimate refresh kills it; an attacker holding a stale token
    # can no longer use it. Requires the token_blacklist app + migrations.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Keep User.last_login current so the "active in last 5 min" badge in
    # the topbar reflects real activity, not just login time.
    'UPDATE_LAST_LOGIN': True,
}


# Media Files — stored on local disk and served by Django at /media/.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB


# Age PREDICTION runs locally (MiVOLO v2 + YOLOv8 + emotion on CPU) — see
# agevision_api/mivolo_predictor.py. No cloud endpoint involved.

# Age PROGRESSION (FADING diffusion) is the only GPU-heavy path that still runs
# on a Modal cloud GPU, because diffusion is impractical on a CPU. Set this to
# the Modal web endpoint URL after running:
#   cd agevision_backend/agevision_api/diffusion_aging && modal deploy modal_app.py
# Can also be set via the FADING_MODAL_ENDPOINT environment variable.
FADING_MODAL_ENDPOINT = os.environ.get(
    'FADING_MODAL_ENDPOINT',
    'https://neerajbhuvanmnb--agevision-fading-age-face-endpoint.modal.run'
)
